import {
  BORDER_RADIUS,
  DARK_GRAY_COLOR,
  LIGHT_GRAY_COLOR,
  PRIMARY_COLOR,
  SECONDARY_COLOR,
} from './style';
import { PROFILE_CREATE, PROFILE_LOGIN } from './endpoints';
import { PROFILE, SIGN_UP, FORGOT_PASSWORD } from './routers';

export {
  BORDER_RADIUS,
  DARK_GRAY_COLOR,
  LIGHT_GRAY_COLOR,
  PRIMARY_COLOR,
  SECONDARY_COLOR,
  PROFILE_CREATE,
  PROFILE_LOGIN,
  PROFILE,
  SIGN_UP,
  FORGOT_PASSWORD,
};
