import {
  BORDER_RADIUS,
  DARK_GRAY_COLOR,
  LIGHT_GRAY_COLOR,
  PRIMARY_COLOR,
  SECONDARY_COLOR,
} from './style';

export {
  BORDER_RADIUS,
  DARK_GRAY_COLOR,
  LIGHT_GRAY_COLOR,
  PRIMARY_COLOR,
  SECONDARY_COLOR,
};
